services:
  db:
    image: postgres:16-alpine
    container_name: catchit-db
    environment:
      POSTGRES_DB: catchitdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - catchit_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d catchitdb"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: catchit-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/catchitdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend/catchit-mobile
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8080
    container_name: catchit-frontend
    ports:
      - "9000:80"
    depends_on:
      backend:
        condition: service_started

volumes:
  catchit_postgres_data:
