server.port=${SERVER_PORT:8081}

spring.config.import=optional:file:../.env[.properties],optional:file:.env[.properties]

spring.datasource.url=${PAYMENT_DB_URL:${DB_URL:jdbc:postgresql://localhost:${DB_PORT:5433}/catchitdb}}
spring.datasource.username=${PAYMENT_DB_USER:${DB_USER:postgres}}
spring.datasource.password=${PAYMENT_DB_PASSWORD:${DB_PASSWORD}}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=${PAYMENT_DB_SCHEMA:payment}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
