---
all:
  vars:
    # GKE cluster variables
    gcp_project: abd2025-474614 # ID of GCP Project
    gcp_auth_kind: serviceaccount # Do not change
    gcp_cred_file: inventory/abd2025-474614-0f6559dd27d0.json # Path to service account keys (json file downloaded from GCP)

    gcp_zone: us-central1-a
    gcp_image_type: ubuntu_containerd
    gcp_machine_type: e2-standard-2 # Can be changed if necessary
    gcp_disk_size_gb: 100 # Can be changed if necessary
    gcp_initial_node_count: 2 # Number of nodes to create. Can be changed if necessary



    # App variables
    app_ip: 35.202.200.2
    app_port: 9000

    # Additional variables
    # ...
    catchit_jwt_token: "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4ZDRjNTg2Ny0yOTg2LTRkYjItYjg3MC1lY2FiNDM2NzE3NmIiLCJlbWFpbCI6InRlc3RlQHVtaW5oby5wdCIsImlhdCI6MTc4MTExMjkyNSwiZXhwIjoxNzgxMTE0NzI1fQ.B3J39ljHwOj6W89T3NJN9pGaHNl7TTn06TOXa9cUrQ4"
    db_name: catchitdb
    db_username: catchit_user
    db_password: catchit_secret
    db_image: postgres:16-alpine
    