---
all:
  vars:
    # GKE cluster variables
    gcp_project: abd2025-474614 # ID of GCP Project
    gcp_auth_kind: serviceaccount # Do not change
    gcp_cred_file: inventory/abd2025-474614-0f6559dd27d0.json # Path to service account keys (json file downloaded from GCP)

    gcp_zone: us-central1-a
    gcp_image_type: ubuntu_containerd
    gcp_machine_type: e2-standard-2 # Can be changed if necessary
    gcp_disk_size_gb: 100 # Can be changed if necessary
    gcp_initial_node_count: 2 # Number of nodes to create. Can be changed if necessary



    # App variables
    app_ip: 34.10.97.42
    app_port: 9000

    # Additional variables
    # ...
    catchit_jwt_token: "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3Mjk3YTBkMS1lMDZiLTQzYTMtYjdiOC0zMGRhMTQ1N2Y4MTgiLCJlbWFpbCI6InRlc3RlQHVtaW5oby5wdCIsImlhdCI6MTc4MTQ2NDQ2MiwiZXhwIjoxNzgxNDY2MjYyfQ.PpCpHqafk33WeAUKdK8IcB-r65LI23gAYPPIXhpP-cg"
    db_name: catchitdb
    db_username: catchit_user
    db_password: catchit_secret
    db_image: postgres:16-alpine
    
    payment_ip: 34.30.200.151
