apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: default
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: "{{ db_image | default('postgres:16-alpine') }}"
        env:
        - name: POSTGRES_DB
          value: "{{ db_name | default('catchitdb') }}"
        - name: POSTGRES_USER
          value: "{{ db_username | default('postgres') }}" 
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: catchitdb-vault 
              key: DB_PASSWORD 
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc