apiVersion: apps/v1
kind: Deployment
metadata:
  name: catchit-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catchit-backend
  template:
    metadata:
      labels:
        app: catchit-backend
    spec:
      containers:
      - name: backend
        image: "{{ catchit_backend_image }}"
        env:
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: catchitdb-vault
              key: DB_PASSWORD
        - name: SPRING_DATASOURCE_URL
          # Ajustado para bater no serviço 'postgres' que está UP no teu cluster
          value: "jdbc:postgresql://postgres-service:5432/{{ db_name | default('catchitdb') }}?currentSchema=catchit"
        - name: SPRING_DATASOURCE_USERNAME
          value: "{{ db_username | default('postgres') }}"
        - name: SPRING_DATA_REDIS_HOST
          # Ajustado para bater no serviço 'catchit-redis' que está UP no teu cluster
          value: "catchit-redis"
        - name: SPRING_DATA_REDIS_PORT
          value: "6379"
        - name: JWT_SECRET
          value: "catchitsecret"
        - name: JWT_EXPIRATION
          value: "1800000"
        - name: SCRIPT_MOCK_DATA_DIR
          value: "/script_mock_data/data"
        ports:
        - containerPort: 8080