apiVersion: v1
kind: Service
metadata:
  name: catchit-otp-service
  namespace: default
  labels:
    app: catchit-otp
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: catchit-otp