apiVersion: apps/v1
kind: Deployment
metadata:
  name: catchit-otp
  namespace: default
  labels:
    app: catchit-otp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catchit-otp
  template:
    metadata:
      labels:
        app: catchit-otp
    spec:
      containers:
      - name: otp
        image: "{{ catchit_otp_image }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        
        resources:
          requests:
            memory: "4Gi"
            cpu: "1000m"
          limits:
            memory: "7Gi" 
            cpu: "2000m"

        livenessProbe:
          httpGet:
            path: /otp
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /otp
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 15