apiVersion: apps/v1
kind: Deployment
metadata:
  name: catchit-payment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catchit-payment
  template:
    metadata:
      labels:
        app: catchit-payment
    spec:
      containers:
      - name: payment-service
        image: "{{ catchit_payment_image | default('rodrigues17/catchit-payment:latest') }}"
        imagePullPolicy: Always
        env:
        # Usa o nome de variável que o teu grupo definiu no docker-compose
        - name: PAYMENT_DB_URL
          value: "jdbc:postgresql://postgres-service:5432/{{ db_name | default('catchitdb') }}?currentSchema=payment"
        - name: PAYMENT_DB_USER
          value: "{{ db_username | default('postgres') }}"
        - name: PAYMENT_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: catchitdb-vault
              key: DB_PASSWORD
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "768Mi"
            cpu: "1000m"

        livenessProbe:
          httpGet:
            path: /api/payments/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/payments/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
